In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {
        'A':[1, np.nan, 3, 4, 5],
        'B':[6, 7, 8, np.nan, 10],
        'C':[11, 12, 13, 14, 15],
    }
)
df

A     B   C
0  1.0   6.0  11
1  NaN   7.0  12
2  3.0   8.0  13
3  4.0   NaN  14
4  5.0  10.0  15

In [2]:
df.isnull()

A      B      C
0  False  False  False
1   True  False  False
2  False  False  False
3  False   True  False
4  False  False  False

In [3]:
from sklearn.impute import SimpleImputer

imp = SimpleImputer(strategy='mean')
imp.fit(df)

imp.transform(df)

array([[ 1.  ,  6.  , 11.  ],
       [ 3.25,  7.  , 12.  ],
       [ 3.  ,  8.  , 13.  ],
       [ 4.  ,  7.75, 14.  ],
       [ 5.  , 10.  , 15.  ]])

In [4]:
df2 = pd.DataFrame({
    'A':[1, 2, 3, 4, 5],
    'B':['a', 'b', 'a', 'b', 'c'],
})
df2

A  B
0  1  a
1  2  b
2  3  a
3  4  b
4  5  c

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(df2['B'])
le.transform(df2['B'])

array([0, 1, 0, 1, 2])

In [6]:
le.classes_

array(['a', 'b', 'c'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

df_two = df2.copy()
le = LabelEncoder()

df_two['B'] = le.fit_transform(df_two['B'])
ohe = OneHotEncoder(categories='auto', sparse=False)

ohe.fit_transform(df_two)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1.]])

In [8]:
df3 = pd.DataFrame({
    'A':[1, 2, 3, 4, 5],
    'B':[100, 200, 400, 500, 800]
})
df3

A    B
0  1  100
1  2  200
2  3  400
3  4  500
4  5  800

In [9]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
stdsc.fit(df3)
stdsc.transform(df3)

array([[-1.41421356, -1.22474487],
       [-0.70710678, -0.81649658],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.40824829],
       [ 1.41421356,  1.63299316]])

In [10]:
from sklearn.preprocessing import MinMaxScaler

mmsc = MinMaxScaler()
mmsc.fit(df3)
mmsc.transform(df3)

array([[0.        , 0.        ],
       [0.25      , 0.14285714],
       [0.5       , 0.42857143],
       [0.75      , 0.57142857],
       [1.        , 1.        ]])